### ISSUE TITLE
메인홈 뷰 구현

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#10]
## Description

메인홈 뷰 구현하기

## To-do

- [x] 프로필 뷰로 넘어가는 버튼 구현
- [x] 누적 정리 확인 뷰로 넘어가는 버튼 구현
- [ ] 내부 뷰 구현
- [ ] 프로그래스바 구현 및 애니메이션 적용
- [ ] 정리를 위한 입력 뷰로 넘어가는 버튼 구현
