### ISSUE TITLE
SelectCapacity의 TipView 디자인 수정

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#107]
## Description
팁 버튼의 가독성을 높이고, 포맷과 연동하여 삭제해야 할 사진, 동영상의 량을 보여주도록 바꾸기

## To-do
- [x] CapacitySettingView의 TipButton 굵기 바꾸기
- [x] TipView 디자인 변경하기
- [x] TipView에 포맷 가져오기
- [x] TipView에 포맷에 맞춰서 삭제해야 할 사진과 동영상 다르게 보이게 설정

## ETC (참고 자료)
![기본화질 팁](https://github.com/user-attachments/assets/e17d1404-bf44-456a-8787-4308e9413de7)
