### ISSUE TITLE
Asset 폴더와 이름을 정리하기

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#109]
## Description
에셋에 있는 폰트와 이미지 파일들을 정리합니다.

## To-do
- [x] 컬러, 이미지 따로 폴더링하기
- [x] mockup용 이미지 - 뉴진스 삭제하기 (관련 preview있으면 그 부분도 제거하기)
- [ ] 에셋 명을 모두 lowerCamelCase로 수정하기
- [x] 하나 수정할 때마다 refactor rename으로 전체 파일에서 이름 바꿔주기 (에러없는지 추가 체크하기)
