### ISSUE TITLE
입력 뷰 생성

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#12]
## Description
정리작업을 진행하기 위한 용량 기준을 입력받는 화면을 만든다.

## To-do
- [x] 고화질 입력화면과 기본화질 입력화면 분리하기
- [x] slider gb 표시자 만들기
- [ ] slider 햅틱 추가하기
- [ ] Tip 화면 만들기

**Comment by Seon-U** [comment]
Tip화면과 CustomSlider, 전체적인 입력뷰 디테일은 이슈를 따로 생성했습니다!
