### ISSUE TITLE
view 리팩토링 및 에러 수정

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#120]
## Description

뷰의 작은 에러를 수정하고, 컴포넌트를 분리하여 구조를 개선합니다.

## To-do

- [ ] **메인 뷰 프로필 버튼 위치 수정하기**  
<img src="https://github.com/user-attachments/assets/b302e5cf-3326-4f6d-9b70-6a053fa7a802" width="130"/>  
<img src="https://github.com/user-attachments/assets/d75fcc37-5f77-40d6-9916-7eb703f72dde" width="130"/>

- [x] **권한 얼럿 빈 화면 이슈 해결하기**  
<img src="https://github.com/user-attachments/assets/b01a0509-1097-4beb-8a34-ec23efa0aa7b" width="130"/>

- [x] **바텀 버튼 컴포넌트화 및 크기 일관성 유지하기**  

## ETC (참고 자료)
