### ISSUE TITLE
lottie 애니메이션 뷰 구현

### ISSUE THREAD

**Issue by zaehorang** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#17]
## Description

lottie를 사용해서 애니메이션을 보여주는 뷰를 구현합니다.

## To-do

- [ ] lottie 라이브러리 spm으로 주입하기
- [ ] 정리 시작을 알리는 뷰 그리기
- [ ] 정리 중 보이는 뷰 그리기
