### ISSUE TITLE
Dynamic Island 구현 로직 만들기

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#2]
## Description

Dynamic Island 생성, 업데이트, 종료 로직 만들기

## To-do

- [x] 다이나믹 아일랜드 생성 로직 만들기
- [x] 다이나믹 아일랜드 업데이트 로직 만들기
- [x] 다이나믹 아일랜드 종료 로직 만들기
