### ISSUE TITLE
TipView, CustomSlider 등 입력뷰 디테일 수정

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#20]
## Description
입력화면과 연동되어 보이는 안내화면, TipView를 만들고 입력뷰 디테일을 수정합니다.  

## To-do
- [ ] TipView 화면 만들기
- [ ] CapacityDirectInputView에서 용량 초과 입력 막기
- [ ] CapacityDirectInputView에서 키보드가 올라오면서 뒤 화면이 같이 움직이는 문제 해결하기
- [ ] CustomSlider thumb이 track 끝에 중점을 만나도록 수정하기
- [ ] CustomSlider Haptic 추가하기
- [ ] CustomSldier mark 간격 조정하기
