### ISSUE TITLE
누적 용량 정리뷰 구현

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#23]
## Description

정리 종료 후 누적 뷰 & 홈에서 넘어가는 누적 확인 뷰

## To-do

- [ ] 위 2뷰에서 사용될 누적 확인 사진 뷰 구현
- [ ] 정리 종료 후 누적 뷰 구현
- [ ] 홈에서 넘어가는 누적 확인 구현
