### ISSUE TITLE
Dynamic Island 안에 dynamic island 중지 버튼 만들기

### ISSUE THREAD

**Issue by leesungkug** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#5]
## Description

다이나믹 아일랜드에 버튼을 넣어서 다이나믹 아일랜드가 중단되게 만들기

## To-do

- [ ] 다이나믹 아일랜드에 버튼 넣기
- [ ] 다이나믹 아일랜드 버튼 눌렀을 때 로딩 버튼 넣기
- [ ] 다이나믹 아일랜드 버튼 눌렀을 때 앱의 특정 로직 작동하게 하기
