### ISSUE TITLE
CapacitySettingView profile 데이터와 연동하기

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#53]
## Description

용량 설정 화면에서 프로필 값이 설정되어있을 시 아이돌의 이름과 이미지를 가져오도록 설정하기

## To-do
- [x] 아이돌 이름 값 가져와서 텍스트 대치하기
- [x] tip 화면에 이미지 가져오기
- [x] 직접 입력시 0일 때 색상을 .gray400으로 설정하기
