### ISSUE TITLE
디바이스의 용량을 반환하는 기능 추가하기

### ISSUE THREAD

**Issue by Seon-U** [DeveloperAcademy-POSTECH/2024-MC3-A12-Moon-Crystal#9]
## Description
디바이스의 용량을 반환하는 기능은 추가한다.

## To-do
- [ ] 디바이스의 총용량을 계산하는 기능 추가하기
- [ ] 디바이스의 사용 가능 용량을 계산하는 추가하기
- [ ] 기능을 관리하는 구조 고민하기
